management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
  endpoint:
    health:
      enabled: true
spring:
  jmx:
    enabled: true

tester:
  name: pkch

spring:
  autoconfigure: